import SparkesIcon from "@/components/SparkesIcon";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen text-white"
        }
      >
        <main className="p-4 max-w-2xl mx-auto">
          <header className="flex justify-between my-8 ">
            <a href="" className="flex gap-1">
              <SparkesIcon />
              DS Ai Caption Gen
            </a>
            <nav className="flex gap-6 text-white/80">
              <Link href="/">Home</Link>
              <Link href="/pricing">Pricing</Link>
              <Link href="mailto:contatct@dustin.com">Contact</Link>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
